name: Maven Central Distribution
on:
  release:
    types: [ published ]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and publish to mavenCentral
        env:
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_KEY: ${{ secrets.OSSRH_KEY }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEYID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.GPG_KEY_CONTENTS }}
        run: ./gradlew publish -PlibraryPublish
